name: generate-android-apk

on:
  workflow_dispatch:

jobs:
  generate-starship-otr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ gcc libzip-dev zipcmp zipmerge ziptool libgl1-mesa-dev
      - name: Install latest SDL
        run: |
          if [ ! -d "SDL2-2.28.5" ]; then
            wget https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-2.28.5.tar.gz
            tar -xzf SDL2-2.28.5.tar.gz
          fi
          cd SDL2-2.28.5
          ./configure --enable-hidapi-libusb
          make -j 10
          sudo make install
          sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
      - name: Install latest tinyxml2
        run: |
          sudo apt-get remove libtinyxml2-dev
          if [ ! -d "tinyxml2-10.0.0" ]; then
            wget https://github.com/leethomason/tinyxml2/archive/refs/tags/10.0.0.tar.gz
            tar -xzf 10.0.0.tar.gz
          fi
          cd tinyxml2-10.0.0
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install
      - name: Generate starship.o2r
        run: |
          cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build-cmake --config Release --target GenerateStarshipOtr -j3
      - uses: actions/upload-artifact@v4
        with:
          name: starship.o2r
          path: starship.o2r
          retention-days: 1

  build-android:
    needs: generate-starship-otr
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build
      - name: Download starship.o2r
        uses: actions/download-artifact@v4
        with:
          name: starship.o2r
          path: Android/app/src/main/assets
      - name: Build Starship APK
        run: |
          cd Android/
          ./gradlew assembleDebug -P elfBuildType=RelWithDebInfo
          mv app/build/outputs/apk/debug/app-debug.apk ../starship.apk
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: starship-apk
          path: starship.apk
