name: Android Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: sudo apt-get install -y ninja-build

      - name: Give gradlew permissions
        run: chmod +x Android/gradlew

      - name: Build Starship APK
        run: |
          cd Android
          ./gradlew assembleDebug -P elfBuildType=RelWithDebInfo
          mv app/build/outputs/apk/debug/app-debug.apk starship.apk
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: starship-apk
          path: starship.apk
