name: Test libultraship Build

on:
  workflow_dispatch:

jobs:
  build-libultraship:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout libultraship
        run: |
          git clone --depth=1 https://github.com/Waterdish/libultraship.git

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ gcc libsdl2-dev libtinyxml2-dev libgl1-mesa-dev libzip-dev unzip

      - name: Configure and Build
        run: |
          cd libultraship
          cmake -H. -Bbuild -G Ninja
          cmake --build build -- -j$(nproc)